import type { ModelScore } from "@/types";

export interface DebateRoundEntry {
  round_no: number;
  provider: string;
  display_name: string;
  content: string;
  latency_ms: number;
}

export interface JudgeData {
  winner: string;
  scores: Record<string, ModelScore>;
  summary: string;
}

export interface ConsensusData {
  final_answer: string;
  confidence_score: number;
}

export function debateToMarkdown(
  topic: string,
  rounds: DebateRoundEntry[],
  judge: JudgeData | null,
  consensus: ConsensusData | null,
): string {
  const date = new Date().toLocaleDateString("ko-KR", {
    year: "numeric", month: "2-digit", day: "2-digit",
  });

  const models = [...new Set(rounds.map((r) => r.display_name))];
  const maxRound = rounds.length > 0 ? Math.max(...rounds.map((r) => r.round_no)) : 0;

  const lines: string[] = [
    "# AI Arena 토론",
    "",
    `**주제**: ${topic}`,
    `**날짜**: ${date}`,
    `**참가 모델**: ${models.join(", ") || "-"}`,
    "",
    "---",
    "",
  ];

  // 라운드별 내용
  for (let r = 1; r <= maxRound; r++) {
    lines.push(`## Round ${r}`, "");
    const roundEntries = rounds.filter((e) => e.round_no === r);
    for (const entry of roundEntries) {
      lines.push(`### ${entry.display_name}`, "");
      lines.push(entry.content, "");
      lines.push(`> ⏱ ${(entry.latency_ms / 1000).toFixed(1)}s`, "");
    }
    lines.push("---", "");
  }

  // 심사 결과
  if (judge) {
    lines.push("## 심사 결과", "");
    if (judge.winner) {
      lines.push(`**승자**: ${judge.winner}`, "");
    }

    const scoreEntries = Object.entries(judge.scores);
    if (scoreEntries.length > 0) {
      lines.push("| 모델 | 정확성 | 논리 | 근거 | 창의성 | 실현가능성 | 합계 |");
      lines.push("|------|--------|------|------|--------|------------|------|");
      for (const [provider, s] of scoreEntries) {
        const name = s.display_name ?? provider;
        lines.push(
          `| ${name} | ${s.accuracy} | ${s.logic} | ${s.evidence} | ${s.creativity} | ${s.feasibility} | **${s.total}** |`
        );
      }
      lines.push("");
    }

    lines.push("**심사 요약**", "");
    lines.push(judge.summary, "");
    lines.push("---", "");
  }

  // 합의 결론
  if (consensus) {
    lines.push("## 합의 결론", "");
    lines.push(`**신뢰도**: ${Math.round(consensus.confidence_score * 100)}%`, "");
    lines.push(consensus.final_answer, "");
    lines.push("---", "");
  }

  lines.push("", `*Generated by [AI Arena](http://localhost)*`);

  return lines.join("\n");
}

export function sanitizeFilename(name: string): string {
  return name.replace(/[/\\?%*:|"<>]/g, "_").slice(0, 40).trim();
}
